title: ELV 2026
description: Course Website
theme: just-the-docs

url: https://embodied-learning-vision-course.github.io

sass:
  quiet_deps: true

aux_links:
  
footer_content:
# Collections for website data
collections:
  staffers:

defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/images/'
